version: '3.8'
services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: hotelix_test
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data: